### PR TITLE
Adding support for '--nodes' on Zuul-CI source

### PR DESCRIPTION
**Pull request by jsanemet**
- Displaying list of nodes under the --spec and --nodes arguments.
- Allowing filtering on --nodes argument.

### CODE REVIEW

**Comment by cescgina** [comment]
I just have a tiny nitpick: I'm not able to see where the node name is set, but can we use a hyphen instead of an underscore? So, instead  of `compute_0` having `compute-0`. That would be consistent with the Jenkins source and IMHO looks better when printed. Other than that, the PR looks great!

**Comment by cescgina** [comment]
Ah ok, if the names comes from tripleo then we can leave it like it is and then we can think later whether we want to make any change.

**Review by cescgina — APPROVED** [review]

**Comment by adrianfusco** [comment]
> I just have a tiny nitpick: I'm not able to see where the node name is set, but can we use a hyphen instead of an underscore? So, instead of `compute_0` having `compute-0`. That would be consistent with the Jenkins source and IMHO looks better when printed. Other than that, the PR looks great!

Sorry for the question, but do we really want to change how the information come from the Zuul source? Maybe having consistent naming between elasticsearch and Jenkins sources is okay. But knowing this is a totally different source is it okay to modify the origin of the naming?

**Review by adrianfusco — APPROVED** [review]
It looks good from me +1

**Comment by adrianfusco** [comment]
> @adrianfusco in my first comment I thought the name was constructed in the cibyl side, but seeing that it comes from the actual zuul instance I agree it's fine to leave it like it is.

Oh, I got it. Thank you Joan. I'm going to merge.

**Pull request merged**
