### PR TITLE
Enabling stdout on integration tests.

### PR DESCRIPTION
**Pull request by jsanemet**
Disabling it crashes PyCharm's test runner.

### CODE REVIEW

**Comment by cescgina** [comment]
Would redirecting stdout to dev/null as shown [here](https://stackoverflow.com/a/45669280) work for pycharm? We don't need the context manager, just redirect and revert in setUp and tearDown methods

**Comment by jsanemet** [comment]
As long as sys.stdout is not None it should be enough.

**Comment by cescgina** [comment]
If that's is ok with you, I'll commit a fix for it with this proposal in this PR

**Comment by jsanemet** [comment]
All right

**Comment by jsanemet** [comment]
That works with PyCharm, you may approve the request and we can merge it then.

**Review by cescgina — APPROVED** [review]
Thanks for bringing it up!

**Pull request merged**
