### PR TITLE
CI Fixes: added requirements.txt, disable pylint 

### PR DESCRIPTION
**Pull request by amolkahat**
- Fixed path in .pre-commit-config.yaml
- Disable pylint until we are good with the code.
- Added yamllint file
- Modified pipeline.yaml
- Added requirements.txt

### CODE REVIEW

**Comment by bregman-arie** [comment]
@amolkahat do we want to close this one?

**Comment by amolkahat** [comment]
@bregman-arie no. not yet. Need to fix linting.

**Comment by amolkahat** [comment]
@bregman-arie now it is ready to merge.

**Comment by bregman-arie** [comment]
@amolkahat looks good! thanks for the effort :)

**Pull request merged**
