### PR TITLE
Add initial Jenkins source

### PR DESCRIPTION
**Pull request by bregman-arie**
* Add generic source interface
* Add generic jenkins client source
* Add OSP jenkins client source

### CODE REVIEW

**Comment by adrianfusco** [comment]
> @adrianfusco sharing with you this very initial draft of Jenkins source I've started to work on in case we find some commonality between elasticsearch and jenkins that we might want to capture in higher-level abstraction (like generic Source class)

Perfect! I'll check it.

**Comment by adrianfusco** [comment]
This draft LGTM. I'll be waiting for more changes.

**Comment by cescgina** [comment]
I have added some functionality to the jenkins source (can connect and query for jobs and builds) and I feel like now it is ready for review

**Comment by bregman-arie** [comment]
Really great job...merging

**Pull request merged**
