### PR TITLE
Adding job variants to the Zuul hierarchy

### PR DESCRIPTION
**Pull request by jsanemet**

### CODE REVIEW

**Review by cescgina — CHANGES_REQUESTED** [review]
Running cibyl --jobs crashes if a jenkins system is used, since the openstack plugin is not included to the original Job class:
```python
Traceback (most recent call last):
  File "/home/jgilaber/redhat/cibyl/.venv/cibyl/bin/cibyl", line 33, in <module>
    sys.exit(load_entry_point('Cibyl', 'console_scripts', 'cibyl')())
  File "/home/jgilaber/redhat/cibyl/cibyl/cli/main.py", line 120, in main
    orchestrator.publisher.publish(
  File "/home/jgilaber/redhat/cibyl/cibyl/publisher.py", line 44, in publish
    print(printer.print_environment(env))
  File "/home/jgilaber/redhat/cibyl/cibyl/models/ci/printers/colored.py", line 71, in print_environment
    printer.add(self.print_system(system), 1)
  File "/home/jgilaber/redhat/cibyl/cibyl/models/ci/printers/colored.py", line 87, in print_system
    printer.add(self._print_jobs_system(system), 0)
  File "/home/jgilaber/redhat/cibyl/cibyl/models/ci/printers/colored.py", line 100, in _print_jobs_system
    printer.add(self.print_job(job), 1)
  File "/home/jgilaber/redhat/cibyl/cibyl/models/ci/printers/colored.py", line 241, in print_job
    attribute = getattr(job, plugin)
AttributeError: 'Job' object has no attribute 'deployment'
```

**Comment by cescgina** [comment]
I've looked at it and changing the _extend method of the plugins/openstack/__init__.py for the version below works (passes all unit, intr and e2e tests). Thinking about it, I think that the loop in the current version ([link](https://github.com/rhos-infra/cibyl/blob/a5f11feb3a6af4a028280fe0308c8d2748f402d2/cibyl/plugins/openstack/__init__.py#L35)) in unnecessary, since we are dealing with class-level attributes anyway. What do you think @bregman-arie ?
```python
    def _extend(self, model_name):                                                                                                                                                      
         for job_class in [Job, ZuulJob]:                                                                                                                                                
            job_class.API['deployment'] = {                                                                                                                                             
                 'attr_type': Deployment,                                                                                                                                                
                 'arguments': [Argument(                                                                                                                                                 
                     name="--deployment",                                                                                                                                                
                     arg_type=str,                                                                                                                                                       
                    nargs="*",                                                                                                                                                          
                     description="Openstack deployment")]}                                                                                                                               
             job_class.plugin_attributes.update(                                                                                                                                         
                     self.plugin_attributes_to_add)                                                                                                                                      
             setattr(job_class, 'add_deployment',                                                                                                                                        
                     add_deployment)

**Comment by bregman-arie** [comment]
> I've looked at it and changing the _extend method of the plugins/openstack/**init**.py for the version below works (passes all unit, intr and e2e tests). Thinking about it, I think that the loop in the current version ([link](https://github.com/rhos-infra/cibyl/blob/a5f11feb3a6af4a028280fe0308c8d2748f402d2/cibyl/plugins/openstack/__init__.py#L35)) in unnecessary, since we are dealing with class-level attributes anyway. What do you think @bregman-arie ?
> 
> ```python
>     def _extend(self, model_name):                                                                                                                                                      
>          for job_class in [Job, ZuulJob]:                                                                                                                                                
>             job_class.API['deployment'] = {                                                                                                                                             
>                  'attr_type': Deployment,                                                                                                                                                
>                  'arguments': [Argument(                                                                                                                                                 
>                      name="--deployment",                                                                                                                                                
>                      arg_type=str,                                                                                                                                                       
>                     nargs="*",                                                                                                                                                          
>                      description="Openstack deployment")]}                                                                                                                               
>              job_class.plugin_attributes.update(                                                                                                                                         
>                      self.plugin_attributes_to_add)                                                                                                                                      
>              setattr(job_class, 'add_deployment',                                                                                                                                        
>                      add_deployment) 
> ```

You are right.  In the previous version, we performed a check if the model is Job in order to associate them, so the loop doesn't seems to be necessary

**Comment by jsanemet** [comment]
Could you please commit your fix then and then we can merge this?

**Comment by cescgina** [comment]
Sure, I'll do it

**Review by cescgina — APPROVED** [review]
Now everything seems to work well, +1

**Pull request merged**
