### PR TITLE
Support --test-result and --test-duration in Jenkins

### PR DESCRIPTION
**Pull request by cescgina**
The Jenkins source can now filter tests by result (case-insensitive
check) and by duration (range check) and by test names (specified in the
--tests argument).

### CODE REVIEW

**Comment by adrianfusco** [comment]
@cescgina I was trying to use it but I can't do the filtering:

```
 (test_filtering_jenkins)$ -> clear; cibyl -d -vvv --sources jenkins --jobs DFG-network-networking-ovn-17.0_director-rhel-virthost-3cont_2comp_1ipa-ipv4-vlan-tls --tests --builds 12 --test-status faIled

Environment: osp_phases
  System: osp_jenkins (type: jenkins)
      Job: DFG-network-networking-ovn-17.0_director-rhel-virthost-3cont_2comp_1ipa-ipv4-vlan-tls
        URL: ...
        Build: 12
          Status: UNSTABLE
          Duration: 347.26m
          Test: test_...
...
```

**Review by adrianfusco — APPROVED** [review]
It looks good to me. It's good to remember that the `--time-duration` should be passed in seconds, it will be converted to ms and the output is in minutes.

+1.

**Review by bregman-arie — CHANGES_REQUESTED** [review]
Following @adrianfusco comment, let's specify the time unit in argument's description

**Comment by cescgina** [comment]
Good catch, thanks @adrianfusco I've updated the description in the documentation to specify that the --test-duration argument uses seconds

**Comment by bregman-arie** [comment]
> Good catch, thanks @adrianfusco I've updated the description in the documentation to specify that the --test-duration argument uses seconds

Do you think we can also mention it in the Test model, in the description of the argument?

**Comment by cescgina** [comment]
Sure, done

**Review by bregman-arie — APPROVED** [review]

**Pull request merged**
