### PR TITLE
Add Test model to CI models

### PR DESCRIPTION
**Pull request by cescgina**
Add a simple Test model, that includes name, status and duration as
attributes. In this future this should likely be further extended, but
this initial version should allow to develop the get_tests method in the
sources.

### CODE REVIEW

**Review by JoseSilvaHermida — APPROVED** [review]
Good job!

**Comment by adrianfusco** [comment]
@cescgina it looks amazing. I have one question, shouldn't be the documentation updated with these arguments?

**Comment by cescgina** [comment]
I have added a brief description of the model to the documentation. If you mean that it's not visible in readthedocs, once merge it'll eventually appear there

**Comment by adrianfusco** [comment]
> I have added a brief description of the model to the documentation. If you mean that it's not visible in readthedocs, once merge it'll eventually appear there

Oh, sorry, I mean in the matrix.

**Comment by cescgina** [comment]
The matrix should be updated once they are supported by a source. Currently no source supports them yet.

**Review by adrianfusco — APPROVED** [review]
Nice then, for me it can be merged. Thanks Joan!

**Pull request merged**
