### PR TITLE
Retrieving release version of a Zuul job

### PR DESCRIPTION
**Pull request by jsanemet**
On this pull request:
- Getting the Zuul source extension to generate a deployment with the job release.
- Extending the variant API to allow access to more information.
- Zuul job model will no longer hold deployments.

### CODE REVIEW

**Comment by bregman-arie** [comment]
Probably not related to this PR but something doesn't quite work for me with this source:
```
INFO     cibyl.orchestrator   Performing query on system zuul_cp
ERROR    cibyl.orchestrator   Error in source: 'zuul_cp' of type: 'zuul' under system: 'zuul_cp'. Reason: 'Unknown error code: '500' returned by host at: https://ZUUL_ADDRESS/zuul/api/tenant/osp/job/opendev-tox-docs. Wait for a couple of minutes and try again...'.
  System: zuul_cp
    No tenants found in query.
```

My config:
```
  component_pipeline:
    zuul_cp:
      system_type: zuul
      sources:
        zuul_cp:
          tenants:
            - osp-internal
          driver: zuul
          url: https://ZUUL_ADDRESS/zuul
```

**Comment by jsanemet** [comment]
It seems that the job simply does not exist, I will need to think of something to output on such case.

**Comment by bregman-arie** [comment]
Still don't able to test this PR. This is what I'm running: ` cibyl --release 16`

```
Environment: component_pipeline
INFO     cibyl.orchestrator   Performing query on system zuul_cp
ERROR    cibyl.orchestrator   Error in source: 'zuul_cp' of type: 'zuul' under system: 'zuul_cp'. Reason: 'Unknown error code: '500' returned by host at: https://ADDRESS/zuul/api/tenant/osp/job/opendev-tox-docs. Wait for a couple of minutes and try again...'.
  System: zuul_cp
    No tenants found in query.
```

This is the configuration I'm using

```
component_pipeline:
    zuul_cp:
      system_type: zuul
      sources:
        zuul_cp:
          driver: zuul
          url: https://ADDRESS/zuul

```

**Comment by jsanemet** [comment]
@bregman-arie In the meantime, you can try using '--spec' instead: cibyl --spec job...

**Comment by bregman-arie** [comment]
Should it work for me at this point?

**Comment by jsanemet** [comment]
Yes, although it will be pretty slow at this point. I suggest filtering jobs as much as possible for the time being.

**Comment by bregman-arie** [comment]
> Yes, although it will be pretty slow at this point. I suggest filtering jobs as much as possible for the time being.

And should it support filtering by value at this point or will that be done in a future PR?

**Comment by jsanemet** [comment]
That will come in a future PR.

**Review by cescgina — APPROVED** [review]

**Comment by bregman-arie** [comment]
I must say, I'm still unable to get the release with 'cibyl --release". Maybe something with my configuration, no idea.

**Pull request merged**
