### PR TITLE
Filter dvr and tls_everywhere true by default

### PR DESCRIPTION
**Pull request by cescgina**
In Jenkins source, the --tls-everywhere and --dvr arguments will by
default a value of True. So using them without any value will print only
those jobs that have tls_everywhere or dvr, respectively. They still
support passing a value, so runing with --dvr False will show only the
jobs that do not use dvr.

### CODE REVIEW

**Review by JoseSilvaHermida — APPROVED** [review]
Works like a charm!

Just one topic: I see that it only works for case-sensitive values, so `cibyl --dvr False` works fine but `cibyl --dvr false` does not return results.

As a user I would prefer a case insensitive value for these True|False arguments

**Review by bregman-arie — APPROVED** [review]
Works great and +2 to what Jose wrote

**Comment by cescgina** [comment]
That's a good point @JoseSilvaHermida, I'll include it since it should be just a small tweak

**Comment by cescgina** [comment]
I've updated the change to make it case insensitive

**Review by bregman-arie — APPROVED** [review]

**Review by JoseSilvaHermida — APPROVED** [review]
Perfect, thanks!

**Pull request merged**
