### PR TITLE
Let each model class have their own set of plugins

### PR DESCRIPTION
**Pull request by jsanemet**
This fixes a bug where Cibyl crashed when it tried to access a plugin on a model that should have never had it in the first place. With this change, each class that inherits from Model gets its own set of plugins, which means that the Zuul job will remain pluginless and will fail no more.

### CODE REVIEW

**Comment by cescgina** [comment]
Before reviewing I want to make sure I understand the change correctly. The problem this fixes is that the two Job classes were sharing the same `plugin_attributes` and by using the new metaclass we make sure that this does not happen because the dictionaries are created whenever a new class is created, is that correct? If that's right, then I think this is a good solution, because even though it's a bit more complex it makes sure the same problem will not be happening again.
What I don't understand is why the two Job classes sharing the plugin_attributes dict caused a crash.

**Comment by bregman-arie** [comment]
I'm still unable to run `cibyl --jobs`

```
Environment: component_pipeline
INFO     cibyl.orchestrator   Performing query on system osp_zuul
INFO     cibyl.orchestrator   Took 169.96s to query system osp_zuul using source: 'zuul_api' of type: 'zuul'
Traceback (most recent call last):
  File "/home/abregman/.cibyl_venv/bin/cibyl", line 10, in <module>
    sys.exit(main())
  File "/home/abregman/cibyl/cibyl/cli/main.py", line 118, in main
    orchestrator.query_and_publish(arguments["output_style"],
  File "/home/abregman/cibyl/cibyl/orchestrator.py", line 329, in query_and_publish
    self.run_query(system)
  File "/home/abregman/cibyl/cibyl/orchestrator.py", line 293, in run_query
    system.populate(model_instances_dict)
  File "/home/abregman/cibyl/cibyl/models/ci/base/system.py", line 164, in populate
    self.add_toplevel_model(model)
  File "/home/abregman/cibyl/cibyl/models/ci/zuul/system.py", line 71, in add_toplevel_model
    self.tenants[key] = model
  File "/home/abregman/cibyl/cibyl/models/attribute.py", line 86, in __setitem__
    self.value[key] = item
TypeError: list indices must be integers or slices, not str
```

**Comment by cescgina** [comment]
I was getting that error too yesterday, this is caused by having a tenant list at the system level in the configuration, which is not supported, it should be at the source level

**Comment by bregman-arie** [comment]
> I was getting that error too yesterday, this is caused by having a tenant list at the system level in the configuration, which is not supported, it should be at the source level

Good to know. I would expect it to be handled similarily to what is done in Jenkins:

```
The following key in "osp_jenkins" system type is not supported: 'tenants'

Check the documentation at https://cibyl.readthedocs.io/en/latest/configuration.html for more information
```

Again one of those points of making sure we have consistent behaviours across systems and sources

**Comment by bregman-arie** [comment]
And I can confirm it works for me now. Thanks @cescgina for the 'tenants' comment.
Thank you @jsanemet for fixing this bug.

**Comment by cescgina** [comment]
The reason that the Zuul system does not fail instead of the Jenkins one is that the constructor of the Zuul system accepts a tenant argument, but it's intended to store `Tenant` models found while querying. While discussing this yesterday with @jsanemet, he suggested verifying the configuration against an schema which should generally solve this kind of bugs, and the task is already in our backlog.

**Comment by jsanemet** [comment]
The thing this fixes is that with the previous implementation all models shared the same plugin dictionary. Meaning that if I installed a plugin on the System model, then I would also see them in Build for example. The metaclass intention is to make each type of model have their own plugin dictionary, so Job will have theirs, Build a different... This way there is no longer a clash between the Jenkins and the Zuul job models.

**Review by adrianfusco — APPROVED** [review]
+1 (if you can add the type hints and the return type it will be nice)

**Pull request merged**
