### PR TITLE
Add ML2 driver type to the spec in jenkins source

### PR DESCRIPTION
**Pull request by cescgina**
Support querying by ml2 driver type in get_deployment and add it to the
spec option.

### CODE REVIEW

**Review by bregman-arie — CHANGES_REQUESTED** [review]
I tried to run spec on a couple of jobs but can't see the ML2 driver:

```
(.cibyl_venv) ➜  cibyl git:(ml2_jenkins_spec) cibyl --spec DFG-hardware_provisioning-rqci-17.0_director-virthost-3cont_2comp_2ironic-ipv4-geneve-IR-OC_Ironic_Introspection 
INFO     cibyl.plugins        Loading plugin: openstack
INFO     cibyl.orchestrator   Took 1.78s to query system jenkins using source jenkins of type jenkins
Environment: osp_jenkins
  System: jenkins
    Job: DFG-hardware_provisioning-rqci-17.0_director-virthost-3cont_2comp_2ironic-ipv4-geneve-IR-OC_Ironic_Introspection
      Openstack deployment: 
        Release: 17.0
        Infra type: virt
        Topology: compute:2,controller:3,ironic:2,undercloud:1
        IP version: 4
        Network backend: geneve
        DVR: True
        TLS everywhere: False
        Storage backend: lvm
        Nodes: 
          - compute-0
          - compute-1
          - controller-0
          - controller-1
          - controller-2
          - ironic-0
          - ironic-1
          - undercloud-0
    Total jobs found in query: 1
(.cibyl_venv) ➜  cibyl git:(ml2_jenkins_spec) cibyl  --spec DFG-network-openstack-designate-16.1_director-rhel-virthost-3cont_2comp-ipv4-geneve                 
INFO     cibyl.plugins        Loading plugin: openstack
INFO     cibyl.orchestrator   Took 1.95s to query system jenkins using source jenkins of type jenkins
Environment: osp_jenkins
  System: jenkins
    Job: DFG-network-openstack-designate-16.1_director-rhel-virthost-3cont_2comp-ipv4-geneve
      Openstack deployment: 
        Release: 16.1
        Infra type: virt
        Topology: controller:3,compute:2
        IP version: 4
        Network backend: geneve
        Nodes: 
          - controller-0
          - controller-1
          - controller-2
          - compute-0
          - compute-1
    Total jobs found in query: 1
```

**Comment by cescgina** [comment]
Interesting, the two jobs represent two different failures. In the first job, the ml2 driver type is not added because both ovn and ovs are set to False, will have to look more in detail about that case because I'm not sure what we should consider it. In the second case, there are no logs captured for the job, so it relies on getting information just from the job name, which is insufficient. Probably we want to raise an error in the second case.

**Comment by bregman-arie** [comment]
> Interesting, the two jobs represent two different failures. In the first job, the ml2 driver type is not added because both ovn and ovs are set to False, will have to look more in detail about that case because I'm not sure what we should consider it. In the second case, there are no logs captured for the job, so it relies on getting information just from the job name, which is insufficient. Probably we want to raise an error in the second case.

1. In that case you might want to consult with Eran on what would be the source of truth if both are False
2. I agree. A warning might be useful. Something along the lines of "Information is based on job name as there are no logs"

**Comment by cescgina** [comment]
I've added a warning for case 2 and will look into case 1 now, thanks for the feedback

**Review by bregman-arie — CHANGES_REQUESTED** [review]
I still don't see ML2 driver:

```
$ cibyl --spec DFG-network-openstack-designate-16.1_director-rhel-virthost-3cont_2comp-ipv4-geneve

INFO     cibyl.plugins        Loading plugin: openstack
WARNING  cibyl.sources.jenkins Some logs are missing for job DFG-network-openstack-designate-16.1_director-rhel-virthost-3cont_2comp-ipv4-geneve, information will be retrieved from the job name, but will be incomplete
INFO     cibyl.orchestrator   Took 2.07s to query system osp_jenkins using source jenkins of type jenkins
Environment: osp_phases
  System: osp_jenkins
    Job: DFG-network-openstack-designate-16.1_director-rhel-virthost-3cont_2comp-ipv4-geneve
      Openstack deployment: 
        Release: 16.1
        Infra type: virt
        Topology: controller:3,compute:2
        IP version: 4
        Network backend: geneve
        Nodes: 
          - controller-0
          - controller-1
          - controller-2
          - compute-0
          - compute-1
    Total jobs found in query: 1
```

**Comment by cescgina** [comment]
This is one of the cases where the logs are not available, so most of the spec is not available. There is a warning logged explaining this, maybe we should list all the spec fields with an 'unknown' value?

**Comment by bregman-arie** [comment]
> This is one of the cases where the logs are not available, so most of the spec is not available. There is a warning logged explaining this, maybe we should list all the spec fields with an 'unknown' value?

Probably, but let's quickly discuss it on our sync

**Comment by cescgina** [comment]
As per the previous discussion, the latest commit used the OSP version to set a default for ml2 driver if it's not set explicitely and sets a consistent spec format. Even if some attributes are not found (e.g because of missing logs), they will be printed with the message "Unable to find information". For example running 
```
$ cibyl  --spec DFG-network-openstack-designate-16.1_director-rhel-virthost-3cont_2comp-ipv4-geneve
Environment: osp_phases
  System: downstream_jenkins
    Job: DFG-network-openstack-designate-16.1_director-rhel-virthost-3cont_2comp-ipv4-geneve
      Openstack deployment: 
        Release: 16.1
        Infra type: virt
        Topology: controller:3,compute:2
        IP version: 4
        Network backend: geneve
        DVR: Unable to find information
        ML2 driver: ovn
        TLS everywhere: Unable to find information
        Storage backend: Unable to find information
        Nodes: 
          - controller-0
          - controller-1
          - controller-2
          - compute-0
          - compute-1
    Total jobs found in query: 1
```

**Comment by bregman-arie** [comment]
> As per the previous discussion, the latest commit used the OSP version to set a default for ml2 driver if it's not set explicitely and sets a consistent spec format. Even if some attributes are not found (e.g because of missing logs), they will be printed with the message "Unable to find information". For example running
> 
> ```
> $ cibyl  --spec DFG-network-openstack-designate-16.1_director-rhel-virthost-3cont_2comp-ipv4-geneve
> Environment: osp_phases
>   System: downstream_jenkins
>     Job: DFG-network-openstack-designate-16.1_director-rhel-virthost-3cont_2comp-ipv4-geneve
>       Openstack deployment: 
>         Release: 16.1
>         Infra type: virt
>         Topology: controller:3,compute:2
>         IP version: 4
>         Network backend: geneve
>         DVR: Unable to find information
>         ML2 driver: ovn
>         TLS everywhere: Unable to find information
>         Storage backend: Unable to find information
>         Nodes: 
>           - controller-0
>           - controller-1
>           - controller-2
>           - compute-0
>           - compute-1
>     Total jobs found in query: 1
> ```

Can I suggest using "N/A" instead of "Unable to find information"? Because "Unable to find" for me, implies that information might be there, but you couldn't find it.

**Comment by cescgina** [comment]
I agree that N/A will be clearer, I've changed it

**Review by bregman-arie — APPROVED** [review]
Perfect. Thank you for adding it.

**Pull request merged**
