### PR TITLE
Reduce the information printed by get_deployment

### PR DESCRIPTION
**Pull request by cescgina**
When querying a Jenkins source for some deploment attribute
(--ip-version, --release, ...) collect only the requested
characteristic, and not everything.

### CODE REVIEW

**Review by bregman-arie — APPROVED** [review]
Works great so I'm going to approve it, but I see lines like this:

```
Job: DFG-compute-nova-openreviews
        Openstack deployment: 
      Job: DFG-compute-python-novaclient-10-pep8-rhos
        Openstack deployment: 
      Job: DFG-compute-python-novaclient-10-unit-rhos
        Openstack deployment: 
```

Do you think we can print something under "openstack deployment"?
@adrianfusco a note that we want to have the same eventually for elasticsearch source

**Comment by adrianfusco** [comment]
> Works great so I'm going to approve it, but I see lines like this:
> 
> ```
> Job: DFG-compute-nova-openreviews
>         Openstack deployment: 
>       Job: DFG-compute-python-novaclient-10-pep8-rhos
>         Openstack deployment: 
>       Job: DFG-compute-python-novaclient-10-unit-rhos
>         Openstack deployment: 
> ```
> 
> Do you think we can print something under "openstack deployment"? @adrianfusco a note that we want to have the same eventually for elasticsearch source

I'll take a look @bregman-arie Thx!

**Comment by cescgina** [comment]
@bregman-arie I have modified the print so a job without any deployment information will be shown like this:
```
      Job: util-stack-janitor-upshift-rhos-qe-ci
          No openstack information associated with this job
      Job: util-weekend-offliner
          No openstack information associated with this job
      Job: util-weekend-temporary-offliner
          No openstack information associated with this job
```

**Comment by bregman-arie** [comment]
> @bregman-arie I have modified the print so a job without any deployment information will be shown like this:
> 
> ```
>       Job: util-stack-janitor-upshift-rhos-qe-ci
>           No openstack information associated with this job
>       Job: util-weekend-offliner
>           No openstack information associated with this job
>       Job: util-weekend-temporary-offliner
>           No openstack information associated with this job
> ```

Perfect. Thank you

**Pull request merged**
